name: Build and deploy Node.js app to Azure Web App - VitrineDeCraquesWeb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Necessário para o login no Azure

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build
        run: npm run build

      - name: Prepare Standalone Package
        run: |
          cp -r public .next/standalone/public
          cp -r .next/static .next/standalone/.next/static

      # AQUI MUDA: Em vez de upload-artifact, já fazemos o login e deploy direto
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_344C4964690740F79447E889D4ECE13C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BA57F9EF5EE9489285A5A9146292AD4A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F2525338E9B49C8B0458A58B5BB40ED }}

      - name: Stop Azure Web App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp stop --name VitrineDeCraquesWeb --resource-group VitrineDeCraques

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'VitrineDeCraquesWeb'
          slot-name: 'Production'
          # Aponta direto para a pasta gerada, sem precisar baixar zip
          package: .next/standalone

      - name: Start Azure Web App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp start --name VitrineDeCraquesWeb --resource-group VitrineDeCraques