name: Deploy Vitrine de Craques Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Next.js Standalone

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Prepare artifact for Azure
        run: |
          mkdir -p azure-dist

          echo "Copying standalone..."
          cp -r .next/standalone azure-dist/

          echo "Copying static assets..."
          mkdir -p azure-dist/.next
          cp -r .next/static azure-dist/.next/static

          echo "Copying public folder..."
          cp -r public azure-dist/public

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: azure-dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to Azure Web App
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: ./deploy-dist

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4F614D4735474B28AD4DEFBDE931C36C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_01417AF951D145B88C5BBE81B95E69BE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4DDB3B84521A4C4092E73E3E9417D990 }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'VitrineDeCraquesWeb'
          package: ./deploy-dist
          startup-command: 'node .next/standalone/server.js'
